### ISSUE TITLE
How long do files persist?

### ISSUE THREAD

**Issue by Farfie** [kimoi/madokami.com#1]
Or am I just blind and can't see the info button? If not, I would really love one. So would random people that don't even know what a "pomf clone" is :)

Also, 256MiB is pretty generous. Exactly what I was looking for, thanks for the work.

**Comment by kimoi** [comment]
Files currently have no expiry, though I am considering adding the option to auto-delete files after a certain amount of time.

There's no FAQ/info page, but I need one. I'll leave this issue open for that.

**Comment by Farfie** [comment]
That sounds very nice. And even better if you could also call that new option through an API of some kind, so that programs like ShareX can take advantage of it too. If you would be so kind, it would be awesome if you added a json file that works with the site here:
https://github.com/ShareX/CustomUploaders

I'm sure one of the pomf clones there are already very close, so it shouldn't take long, and I'd do it myself if I had any idea what was going on...
