### ISSUE TITLE
Install?

### ISSUE THREAD

**Issue by TPBT-OFFICIAL** [kimoi/madokami.com#2]
Im guessing this is the complete script, i know its a pomf clone but it seems to be a lot more complete so i was wondering, whats the exact way to install it if possible someone helping? im willing to donate resources or anything to anyone in need.

**Comment by kimoi** [comment]
In lieu of a complete setup guide, you can take a look at vagrant-provision.sh. This script is designed to be run by Vagrant to create the proper environment.

Work your way through that, though you can skip the rocketeer and hostname setup. If you're not on Debian or you don't want to use Apache then you'll have to alter your approach a bit.

Let me know if you need any more help.

**Comment by TPBT-OFFICIAL** [comment]
Thank you, ill install debian and take a look.
